#!/usr/bin/python3
# Casting Time, Range, Components, Duration, Description
choices = {
        'Acid Splash':     ['1 Action','60 ft',                     'V, S',    'Instantaneous',                'You hurl a bubble of acid. Choose one or two creatures you can see within range.\nIf you choose two, they must be within 5 feet of each other.\nA target must succeed on a Dexterity saving throw or take 1d6 acid damage.\nThis spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).'],
        'Chill Touch':     ['1 Action','120 ft',                    'V, S',    '1 Round',                      'You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can\'t regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn. This spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).'],
        'Create Bonfire':  ['1 Action','60 ft (5 ft cube)',         'V, S',    '1 Minute',                     'You create a bonfire on ground that you can see within range.\nUntil the spell ends, the magic bonfire fills a 5-foot cube.\nAny creature in the bonfire’s space when you cast the spell must succeed on a Dexterity saving throw or take 1d8 fire damage.\nA creature must also make the saving throw when it moves into the bonfire’s space for the first time on a turn or ends its turn there.\nThe bonfire ignites flammable objects in its area that aren’t being worn or carried.\n\nThe spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).'],
        'Fire Bolt':       ['1 Action','120 ft',                    'V, S',    'Instantaneous',                'You hurl a mote of fire at a creature or object within range.\nMake a ranged spell attack against the target.\nOn a hit, the target takes 1d10 fire damage.\nA flammable object hit by this spell ignites if it isn\'t being worn or carried.\nThis spell\'s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).'],
        'Friends':         ['1 Action','Self',                      'S, M*',   'Concentration, Up to 1 Minute','For the duration, you have advantage on all Charisma checks directed at one creature of your choice that isn’t hostile toward you.\nWhen the spell ends, the creature realizes that you used magic to influence its mood and becomes hostile toward you.\nA creature prone to violence might attack you.\nAnother creature might seek retribution in other ways (at the DM ’s discretion), depending on the nature of your interaction with it.\n\n* - (a small amount of makeup applied to the face as this spell is cast)'],
        'Frostbite':       ['1 Action','60 ft',                     'V, S',    'Instantaneous','You cause numbing frost to form on one creature that you can see within range.\nThe target must make a Constitution saving throw.\nOn a failed save, the target takes 1d6 cold damage, and it has disadvantage on the next weapon attack roll it makes before the end of its next turn.\nThe spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).'],
        'Gust':            ['1 Action','30 ft',                     'V, S',    'Instantaneous',                'You seize the air and compel it to create one of the following effects at a point you can see within range:<ul><li>One Medium or smaller creature that you choose must succeed on a Strength saving throw or be pushed up to 5 feet away from you.</li><li>You create a small blast of air capable of moving one object that is neither held nor carried and that weighs no more than 5 pounds. The object is pushed up to 10 feet away from you. It isn’t pushed with enough force to cause damage.</li><li>You create a harmless sensory affect using air, such as causing leaves to rustle, wind to slam shutters shut, or your clothing to ripple in a breeze.</li></ul>'],
        'Minor Illusion':  ['1 Action','30 ft (5 ft cube)',         'S, M*',   '1 Minute',                     'You create a sound or an image of an object within range that lasts for the duration.\nThe illusion also ends if you dismiss it as an action or cast this spell again.\nIf you create a sound, its volume can range from a whisper to a scream.\nIt can be your voice, someone else\'s voice, a lion\'s roar, a beating of drums, or any other sound you choose.\nThe sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends.\nIf you create an image of an object--such as a chair, muddy footprints, or a small chest--it must be no larger than a 5-foot cube.\nThe image can\'t create sound, light, smell, or any other sensory effect.\nPhysical interaction with the image reveals it to be an illusion, because things can pass through it.\nIf a creature uses its action to examine the sound or image, the creature can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC.\nIf a creature discerns the illusion for what it is, the illusion becomes faint to the creature.\n\n* - (a bit of fleece)'],
        'Poison Spray':    ['1 Action','10 ft',                     'V, S',    'Instantaneous',                'You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm.\nThe creature must succeed on a Constitution saving throw or take 1d12 poison damage.\nThis spell\'s damage increases by 1d12 when you reach 5th level (2d12), 11th level (3d12), and 17th level (4d12).'],
        'Ray of Frost':    ['1 Action','60 ft',                     'V, S',    'Instantaneous',                'A frigid beam of blue-white light streaks toward a creature within range.\nMake a ranged spell attack against the target.\nOn a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.\nThe spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).'],
        'Shocking Grasp':  ['1 Action','Touch',                     'V, S',    'Instantaneous',                'Lightning springs from your hand to deliver a shock to a creature you try to touch.\nMake a melee spell attack against the target.\nYou have advantage on the attack roll if the target is wearing armor made of metal.\nOn a hit, the target takes 1d8 lightning damage, and it can\'t take reactions until the start of its next turn.\nThe spell\'s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).'],
        'Thunderclap':     ['1 Action','5 ft',                      'S',       'Instantaneous',                'You create a burst of thunderous sound that can be heard up to 100 feet away.\nEach creature within range, other than you, must succeed on a Constitution saving throw or take 1d6 thunder damage.\nThe spell\’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).'],
        'True Strike':     ['1 Action','30 ft',                     'S',       '1 Round',                      'You point a finger at a target in range.\nYour magic grants you a brief insight into the target\'s defenses.\nOn your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn\'t ended.']
        }
